foreground         #c1c3c5
background         #0a1119
background_opacity 1.0
cursor             #c1c3c5

active_tab_foreground     #0a1119
active_tab_background     #c1c3c5
inactive_tab_foreground   #c1c3c5
inactive_tab_background   #0a1119

active_border_color   #c1c3c5
inactive_border_color #0a1119
bell_border_color     #1b3b54

color0       #0a1119
color8       #59636e
color1       #1b3b54
color9       #254F71
color2       #504b51
color10      #6B646D
color3       #675a5c
color11      #8A797B
color4       #1f4a69
color12      #2A638C
color5       #395772
color13      #4C7598
color6       #3f6883
color14      #558BAF
color7       #8e9298
color15      #c1c3c5
