foreground         #c5c6c7
background         #191c21
background_opacity 1.0
cursor             #c5c6c7

active_tab_foreground     #191c21
active_tab_background     #c5c6c7
inactive_tab_foreground   #c5c6c7
inactive_tab_background   #191c21

active_border_color   #c5c6c7
inactive_border_color #191c21
bell_border_color     #4b5b64

color0       #191c21
color8       #606976
color1       #4b5b64
color9       #657A86
color2       #2d6366
color10      #3D8589
color3       #346366
color11      #468588
color4       #58696a
color12      #768C8E
color5       #777c72
color13      #9FA698
color6       #9d9981
color14      #D2CDAC
color7       #93969e
color15      #c5c6c7
