foreground         #c2c3c6
background         #0D121B
background_opacity 1.0
cursor             #c2c3c6

active_tab_foreground     #0D121B
active_tab_background     #c2c3c6
inactive_tab_foreground   #c2c3c6
inactive_tab_background   #0D121B

active_border_color   #c2c3c6
inactive_border_color #0D121B
bell_border_color     #353e55

color0       #0D121B
color8       #5b626f
color1       #353e55
color9       #475372
color2       #455371
color10      #5D6F97
color3       #724563
color11      #995C84
color4       #536588
color12      #6F87B6
color5       #5a6f98
color13      #7895CB
color6       #6e7faa
color14      #93AAE3
color7       #8f939a
color15      #c2c3c6
