exec-once = swaync-client -df
exec-once = systemctl --user start hyprpolkitagent
exec-once = swww-daemon
exec-once = hypridle
# exec-once = ./Scripts/graphics-tablet-drivers.sh

exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

# Set the cursor to workspace 1 at startup
exec-once = hyprctl dispatch workspace 1
exec-once = waybar &
