input {
    kb_layout = us,it
    kb_variant =
    kb_model =
    kb_rules =
    
    # Change keyboard layout
    # Capslock as super
    kb_options=caps:super, grp:win_space_toggle 

    follow_mouse = 1
    accel_profile=flat

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
        scroll_factor = 0.4
    }
}
gestures {
    workspace_swipe = true
}
