##############################
### WINDOWS AND WORKSPACES ###
##############################

# Ignore maximize requests from apps.
windowrule = suppress_event maximize, match:class .*

# Wofi blur (layer rules)
layerrule = blur on,           match:namespace wofi
layerrule = ignore_alpha 0.5,  match:namespace wofi

# Swaync blur (layer rules)
layerrule = blur on,           match:namespace swaync-control-center
layerrule = blur on,           match:namespace swaync-notification-window
layerrule = ignore_alpha 0.5,  match:namespace swaync-control-center
layerrule = ignore_alpha 0.5,  match:namespace swaync-notification-window

# Floating terminal
windowrule = float on,         match:title ^(floating-terminal)$
windowrule = size 800 500,     match:title ^(floating-terminal)$
windowrule = center on,        match:title ^(floating-terminal)$

# Fix some dragging issues with XWayland
windowrule = no_focus on,      match:class ^$, match:title ^$, match:xwayland yes, match:float yes, match:fullscreen no, match:pin no

# Fix context menu (niente blur)
windowrule = no_blur on,       match:class ^()$, match:title ^()$

# Pulsemixer floating
windowrule = float on,         match:title ^(pulsemixer)$

# Mpv floating
windowrule = float on,         match:class ^(mpv)$

# Workspace Rules
workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = 6, monitor:DP-1
workspace = 7, monitor:DP-1
workspace = 8, monitor:DP-1
workspace = 9, monitor:DP-1
workspace = 10, monitor:DP-1
