##############################
### WINDOWS AND WORKSPACES ###
##############################
# Ignore maximize requests from apps.
windowrulev2 = suppressevent maximize, class:.*

# Wofi blur
layerrule = blur, wofi
layerrule = ignorezero, wofi
layerrule = ignorealpha 0.5, wofi

# Swaync blur
layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-control-center
layerrule = ignorezero, swaync-notification-window
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-window

# Floating terminal
windowrulev2 = float,title:^(floating-terminal)$
windowrulev2 = size 800 500,title:^(floating-terminal)$
windowrulev2 = center,title:^(floating-terminal)

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Fix context menu 
windowrulev2=noblur,class:^()$,title:^()$

# Pusemixer floating
windowrulev2 = float, title:^(pulsemixer)$

# Workspace Rules
workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
